#this file holds the lists of words
word_list = [
  "apple", "banana", "cherry", "date", "elderberry", "fig", "grape", "honeydew",
  "iguana", "jaguar", "kangaroo", "lemur", "mongoose", "narwhal", "octopus", "penguin",
  "quokka", "raccoon", "salamander", "tiger", "umbrella", "vulture", "walrus", "xenops",
  "yak", "zebra", "adventure", "bravery", "courage", "determination", "empathy", "friendship",
  "gratitude", "happiness", "imagination", "joy", "kindness", "love", "motivation", "nostalgia",
  "optimism", "patience", "quiet", "resilience", "serenity", "trust", "understanding", "vitality",
  "wisdom", "yearning", "zeal", "architecture", "bridge", "castle", "dome", "elevator", "fountain",
  "garden", "house", "igloo", "jungle", "kitchen", "library", "mountain", "neighborhood", "ocean",
  "park", "quarry", "river", "skyline", "temple", "universe", "valley", "waterfall", "xylophone",
  "yacht", "zoo", "abstract", "balance", "clarity", "depth", "energy", "focus", "growth", "harmony",
  "identity", "journey", "knowledge", "legacy", "momentum", "network", "opportunity", "potential",
  "quality", "reliability", "strategy", "transformation", "unity", "vision", "wonder", "xenophobia",
  "youth", "zenith", "art", "beauty", "creativity", "design", "expression", "freedom", "gesture",
  "hue", "illustration", "jewel", "kaleidoscope", "landscape", "masterpiece", "nuance", "originality",
  "palette", "quintessence", "rhythm", "style", "texture", "uniqueness", "vividness", "whimsy",
  "factor", "yearbook", "zest", "adventure", "breeze", "cloud", "dawn", "earth", "forest", "glacier",
  "horizon", "island", "jungle", "kaleidoscope", "lake", "meadow", "nebula", "oasis", "prairie",
  "quicksand", "rainbow", "sunset", "tundra", "universe", "volcano", "water", "xenon", "yard",
  "zen", "ambition", "belief", "curiosity", "dedication", "enthusiasm", "faith", "generosity",
  "hope", "integrity", "justice", "kindness", "loyalty", "mindfulness", "nobility", "openness",
  "perseverance", "quest", "respect", "sincerity", "tenacity", "understanding", "virtue", "warmth",
  "xenial", "yearning", "zestful"
]